### ISSUE TITLE
Needs to recognize explore and developer are not users

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#13]

**Comment by JoshuaNeedle** [comment]
I've looked into and have tried removing specifically anything that says developer in the URL right in the JSON file by using "exclude-matches": and "exclude-globs". But there is an existing bug out there for this very issue that another user was having that is still not resolved:
https://bugs.chromium.org/p/chromium/issues/detail?id=100106

Haven't been able to find another solution yet.

**Comment by MSevey** [comment]
added another variable called developer and check against it in the onUserPage

this is done, just need to push my branch
