### ISSUE TITLE
Engagement Rates

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#22]
One of the metrics we want to compute (all computations on the client / plugin) is engagement rate.  This metric tells us how many engagements an influencer gets relative to the number of followers they have.

- [ ] Post Engagement Rate =  (Post Likes + Post Comments) / Follower Count

- [x] Influencer Engagement Rate = Avg Post Engagement Rate for last 90 days or 20 posts, whichever is shorter

**Comment by brookea** [comment]
We are not completing the first (post engagement rate) because it is on per post basis, which we cannot display in our extension.
Instead, we went ahead with average engagement rate by taking average engagement and dividing by followers.
