### ISSUE TITLE
Follower Engagement Rates

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#23]
This metric tells us what percentage of the influencers followers engage when they post.

- [ ] Post Follower Engagement Rate = Unique Followers Who Like or Comment / Follower Count

- [ ] Influencer Follower Engagement Rate = Average Post Follower Engagement Rate for last 90 days or 20 posts, whichever is shorter

**Comment by chanceencounter** [comment]
Doesn't list all followers in JSON.

**Comment by chanceencounter** [comment]
Can't do unique followers anymore. :(
