### ISSUE TITLE
Sponsored Post Rate

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#24]
This metrics tells us what % of the influencers posts appear to be sponsored.

- [x] Sponsored Post Rate = Count of posts that include a ‘sponsored hashtag’ / total number of posts (last 20 or 90 days)

- [x] Sponsored Hashtags :  #sponsored, #ad, #advertisement, #promotion

- [x] https://www.ftc.gov/tips-advice/business-center/guidance/ftcs-endorsement-guides-what-people-are-asking

**Comment by chanceencounter** [comment]
For top 20 posts, done.

**Comment by chanceencounter** [comment]
Sponsored Post Rate: Need to write function for converting epoch time (UNIX CLOCK) to human readable time.

**Comment by chanceencounter** [comment]
Sponsored posts per last 20*

**Comment by chanceencounter** [comment]
If it's for the last 20, done.
