### ISSUE TITLE
Fake Followers

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#26]
TBD

**Comment by brookea** [comment]
http://caleydimmock.com/instahacks-how-to-tell-fake-instagram-followers/

**Comment by MSevey** [comment]
- [ ] Check engagement rate vs # of followers
- [ ] check number of comments to number of likes
- [ ] check followers for accounts that are private and are following significantly more than have followers

**Comment by MSevey** [comment]
need to verify on an account that is none to have no fake followers

**Comment by MSevey** [comment]
How do we want to update the UI?  are we good with just hiding and showing the fake followers or do we have a good / bad logo?

**Comment by MSevey** [comment]
Last to do

- [ ] record if icon was clicked so the user only has to click to find out why the warning once
