### ISSUE TITLE
Instagram trigger

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#3]
Create trigger off of instagram.com

**Comment by chanceencounter** [comment]
Front-end task.

Things you should know:
Know how to traverse the DOM
Should have listeners for hover events
Should understand that it's on a website formatted like instagram.com/[user] and hit the instagram.com/[user]/media endpoint for JSON info.

**Comment by MSevey** [comment]
https://stackoverflow.com/questions/10396634/chrome-extension-run-for-a-specific-page

**Comment by JoshuaNeedle** [comment]
What you posted runs the chrome extension, but does not pop it up. His example would just provide an alert box of "Hello World". Unless I'm misreading it..

https://stackoverflow.com/questions/5544256/chrome-extensionhow-to-pragmatically-open-the-popup-window-from-background-htm
