### ISSUE TITLE
instagram json

### ISSUE THREAD

**Issue by MSevey** [kninja900/kninja900#7]
working on parsing instagram/media to look at post data

**Comment by MSevey** [comment]
jQuery example of parsing json from url 

https://stackoverflow.com/questions/12460378/how-to-get-json-from-url-in-javascript

**Comment by MSevey** [comment]
Accessing json 

https://www.w3schools.com/js/js_json.asp

https://stackoverflow.com/questions/10895306/how-to-access-json-object-name-value

**Comment by chanceencounter** [comment]
"Done" in the sense where we have a JSON object for the media file, however we're still trying to get the API calls working with auth.
