### ISSUE TITLE
Mavrck API

### ISSUE THREAD

**Issue by brookea** [kninja900/kninja900#8]

**Comment by chanceencounter** [comment]
Investigating how to do the workaround with API Auth Tokens.

**Comment by MSevey** [comment]
**From Brian**
The API integration will be via JSON/Rest endpoints.  The endpoints will need to be authenticated via JWT token, provisions via a username/password authentication process.  As part of this project, we can do API design and establish the JSON payload definition, but may not actually complete the authentication loop.  Another option for testing is to manually provision a JWT token and hard code the token for the time being.

**Comment by MSevey** [comment]
`  function sendJSON (json) {
    $.ajax({
        url: "",
        type : 'POST',
        dataType: 'json',
        crossDomain: true, // indicating leaving curren Domain
        data: "{}", // need to stringify json object
        // data: JSON.stringify(json),
        contentType:'text/plain',
        success:function result(data) {
                console.log("Success"); 
                console.log(data); 
        },
        error:function result(msg) {
                console.log("Error"); 
                console.log(msg); 
        }
    });
  }`

the above ajax request seems to give a different error than the security errors we were having.  not sure if this is an improvement or not.

the differences are the crossDomain: true, and making sure data is a string.  So either "{}" or JSON.stringify()

**Comment by MSevey** [comment]
https://stackoverflow.com/questions/5819509/chrome-extension-cross-origin-post-request
